# fly.toml file generated for recipes-api on 2022-08-27T10:01:00-04:00

app = "recipes-api"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  FRONTEND_BASE_URL_IP = "http://192.168.1.129:3000"
  FRONTEND_BASE_URL_LOCAL = "http://localhost:3000"
  FRONTEND_BASE_URL_PROD = "https://glasser-recipes.herokuapp.com"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
